/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * add_student.cc
 * 2024-01-10 22:43:21
 * Generated by rpc framework rpc_generator.py
 * File will not generate while exist
 * Allow editing
****************************************************/


#include <rpc/common/log.h>
#include "student_server/interface/add_student.h"
#include "student_server/interface/interface.h"
#include "student_server/pb/student_server.pb.h"

namespace student_server {

AddStudentInterface::AddStudentInterface(const ::addSyudentRequest* request, ::addSyudentResponse* response, 
    rpc::RpcClosure* done, rpc::RpcController* controller)
  : Interface(dynamic_cast<const google::protobuf::Message*>(request), dynamic_cast<google::protobuf::Message*>(response), done, controller),
    m_request(request), 
    m_response(response) {
  APPINFOLOG("In|request:{%s}", request->ShortDebugString().c_str());
}

AddStudentInterface::~AddStudentInterface() {
  APPINFOLOG("Out|response:{%s}", m_response->ShortDebugString().c_str());
}

void AddStudentInterface::run() {

  //
  // Run your business logic at here
  // 

  m_response->set_ret_code(0);
  m_response->set_res_info("OK");

}

void AddStudentInterface::setError(int code, const std::string& err_info) {
  m_response->set_ret_code(code);
  m_response->set_res_info(err_info);
}

}