/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * add_student.h
 * 2024-01-10 22:43:21
 * Generated by rpc framework rpc_generator.py
 * File will not generate while exist
 * Allow editing
****************************************************/

#ifndef STUDENT_SERVER_INTERFACE_ADD_STUDENT_H
#define STUDENT_SERVER_INTERFACE_ADD_STUDENT_H 

#include <rpc/net/rpc/rpc_closure.h>
#include "student_server/pb/student_server.pb.h"
#include "student_server/interface/interface.h"


namespace student_server {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class AddStudentInterface : public Interface {
 public:

  AddStudentInterface(const ::addSyudentRequest* request, ::addSyudentResponse* response, 
    rpc::RpcClosure* done, rpc::RpcController* controller);

  ~AddStudentInterface();

 public:
  // core business deal method
  virtual void run() override;

  // set error code and error into to response message
  virtual void setError(int code, const std::string& err_info) override;

 private:
  const ::addSyudentRequest* m_request {NULL};       // request object fron client

  ::addSyudentResponse* m_response {NULL};           // response object that reply to client

};


}


#endif