/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * interface.cc
 * 2024-01-10 22:42:27
 * Generated by rpc framework rpc_generator.py
 * File will not generate while exist
 * Allow editing
****************************************************/


#include <rpc/common/log.h>
#include <rpc/net/rpc/rpc_closure.h>
#include <rpc/net/rpc/rpc_closure.h>
#include <rpc/net/rpc/rpc_controller.h>
#include <google/protobuf/message.h>

#include "student_server/interface/interface.h"

namespace student_server {


Interface::Interface(const google::protobuf::Message* req, google::protobuf::Message* rsp, rpc::RpcClosure* done, rpc::RpcController* controller)
  : rpc::RpcInterface(req, rsp, done, controller) {

}

Interface::~Interface() {

}

}