/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * student_server.cc
 * 2024-01-10 22:43:21
 * Generated by rpc framework rpc_generator.py
 * Do not edit !!!
****************************************************/


#include <google/protobuf/service.h>
#include <exception>
#include <rpc/common/log.h>
#include "student_server/pb/student_server.pb.h"
#include "student_server/service/student_server.h"
#include "student_server/comm/business_exception.h"
#include "student_server/interface/add_student.h"
#include "student_server/interface/query_student.h"


#define CALL_RPC_INTERFACE(Type)                                                                                                    \
  {                                                                                                                                 \
    rpc::RpcClosure* clo = dynamic_cast<rpc::RpcClosure*>(done);                                                              \
    rpc::RpcController* con = dynamic_cast<rpc::RpcController*>(controller);                                                  \
    std::shared_ptr<Type> impl = std::make_shared<Type>(request, response, clo, con);                                               \
    rpc::RunTime::GetRunTime()->m_rpc_interface = std::dynamic_pointer_cast<rpc::RpcInterface>(impl).get();                   \
    response->set_ret_code(0);                                                                                                      \
    response->set_res_info("OK");                                                                                                   \
    try {                                                                                                                           \
      impl->run();                                                                                                                  \
    } catch (BusinessException& e) {                                                                                                \
      APPDEBUGLOG("business exception");                                                                                            \
      response->set_ret_code(e.errorCode());                                                                                        \
      response->set_res_info(e.errorInfo());                                                                                        \
    } catch (rpc::RpcException& e) {                                                                                          \
      APPDEBUGLOG("RpcException");                                                                                               \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown RpcException");                                                                            \
    } catch (std::exception& e) {                                                                                                   \
      APPDEBUGLOG("std::exception");                                                                                                \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown std::exception");                                                                             \
    } catch (...) {                                                                                                                 \
      APPDEBUGLOG("... exception");                                                                                                 \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown exception");                                                                                  \
    }                                                                                                                               \
  }                                                                                                                                 \

namespace student_server {

void OrderImpl::add_student(::google::protobuf::RpcController* controller,
                       const ::addSyudentRequest* request,
                       ::addSyudentResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(AddStudentInterface);
}

void OrderImpl::query_student(::google::protobuf::RpcController* controller,
                       const ::queryStudentRequest* request,
                       ::queryStudentResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(QueryStudentInterface);
}



}