/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * student_server.h
 * 2024-01-10 22:43:21
 * Generated by rpc framework rpc_generator.py
 * Do not edit !!!
****************************************************/


#ifndef STUDENT_SERVER_SERVICE_STUDENT_SERVER_H 
#define STUDENT_SERVER_SERVICE_STUDENT_SERVER_H

#include <google/protobuf/service.h>
#include "student_server/pb/student_server.pb.h"

namespace student_server {

class OrderImpl : public Order {

 public:

  OrderImpl() = default;

  ~OrderImpl() = default;

  // override from Order
  virtual void add_student(::google::protobuf::RpcController* controller,
                       const ::addSyudentRequest* request,
                       ::addSyudentResponse* response,
                       ::google::protobuf::Closure* done);

  // override from Order
  virtual void query_student(::google::protobuf::RpcController* controller,
                       const ::queryStudentRequest* request,
                       ::queryStudentResponse* response,
                       ::google::protobuf::Closure* done);

  

};

}


#endif